language: ruby
install:  env BUNDLE_GEMFILE="$(ruby -e 'print File.expand_path %{test/Gemfile}')" bundle install
script:   env BUNDLE_GEMFILE="$(ruby -e 'print File.expand_path %{test/Gemfile}')" bundle exec cucumber -r test/features/ test/features/
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - rbx-2.2.10
